- name: Install Git and copy SSH keys
  hosts: all
  become: yes
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
    - name: Create .ssh directory for ansible-worker
      file:
        path: /home/ansible-worker/.ssh
        state: directory
        owner: ansible-worker
        group: ansible-worker
        mode: '0700'
    - name: Copy SSH private key
      copy:
        src: ssh_keys/id_rsa
        dest: /home/ansible-worker/.ssh/id_rsa
        owner: ansible-worker
        group: ansible-worker
        mode: '0600'
    - name: Copy SSH public key
      copy:
        src: ssh_keys/id_rsa.pub
        dest: /home/ansible-worker/.ssh/id_rsa.pub
        owner: ansible-worker
        group: ansible-worker
        mode: '0644'
